package com.tamin.taminhamrah.mapper.objectionInsurance

import com.tamin.taminhamrah.model.objectionInsurance.ObjectionInsuranceHistoryDN
import com.tamin.taminhamrah.model.objectionInsurance.ObjectionInsuranceHistoryPR

fun ObjectionInsuranceHistoryDN.toPresentation(): ObjectionInsuranceHistoryPR = ObjectionInsuranceHistoryPR(
    branchCode = branchCode.orEmpty(),
    branchName = branchName.orEmpty(),
    confirmed = confirmed ?: false,
    deleted = deleted ?: false,
    historyTypeCode = historyTypeCode.orEmpty(),
    historyTypeName = historyTypeName.orEmpty(),
    isDeleted = isDeleted ?: false,
    newMonth1 = newMonth1.orEmpty(),
    newMonth2 = newMonth2.orEmpty(),
    newMonth3 = newMonth3.orEmpty(),
    newMonth4 = newMonth4.orEmpty(),
    newMonth5 = newMonth5.orEmpty(),
    newMonth6 = newMonth6.orEmpty(),
    newMonth7 = newMonth7.orEmpty(),
    newMonth8 = newMonth8.orEmpty(),
    newMonth9 = newMonth9.orEmpty(),
    newMonth10 = newMonth10.orEmpty(),
    newMonth11 = newMonth11.orEmpty(),
    newMonth12 = newMonth12.orEmpty(),
    oldMonth1 = oldMonth1.orEmpty(),
    oldMonth2 = oldMonth2.orEmpty(),
    oldMonth3 = oldMonth3.orEmpty(),
    oldMonth4 = oldMonth4.orEmpty(),
    oldMonth5 = oldMonth5.orEmpty(),
    oldMonth6 = oldMonth6.orEmpty(),
    oldMonth7 = oldMonth7.orEmpty(),
    oldMonth8 = oldMonth8.orEmpty(),
    oldMonth9 = oldMonth9.orEmpty(),
    oldMonth10 = oldMonth10.orEmpty(),
    oldMonth11 = oldMonth11.orEmpty(),
    oldMonth12 = oldMonth12.orEmpty(),
    prow = prow.orEmpty(),
    requestNumber = requestNumber.orEmpty(),
    requestType = requestType.orEmpty(),
    insuredId = insuredId.orEmpty(),
    workshopId = workshopId.orEmpty(),
    userDesc = userDesc.orEmpty(),
    workshopName = workshopName.orEmpty(),
    year = year,
)

fun List<ObjectionInsuranceHistoryDN>.toPresentation(): List<ObjectionInsuranceHistoryPR> =
    map { it.toPresentation() }

/** The inverse of [toPresentation], needed to rebuild a save payload from what the UI staged. */
fun ObjectionInsuranceHistoryPR.toDomain(): ObjectionInsuranceHistoryDN = ObjectionInsuranceHistoryDN(
    branchCode = branchCode,
    branchName = branchName,
    confirmed = confirmed,
    deleted = deleted,
    historyTypeCode = historyTypeCode,
    historyTypeName = historyTypeName,
    isDeleted = isDeleted,
    newMonth1 = newMonth1,
    newMonth2 = newMonth2,
    newMonth3 = newMonth3,
    newMonth4 = newMonth4,
    newMonth5 = newMonth5,
    newMonth6 = newMonth6,
    newMonth7 = newMonth7,
    newMonth8 = newMonth8,
    newMonth9 = newMonth9,
    newMonth10 = newMonth10,
    newMonth11 = newMonth11,
    newMonth12 = newMonth12,
    oldMonth1 = oldMonth1,
    oldMonth2 = oldMonth2,
    oldMonth3 = oldMonth3,
    oldMonth4 = oldMonth4,
    oldMonth5 = oldMonth5,
    oldMonth6 = oldMonth6,
    oldMonth7 = oldMonth7,
    oldMonth8 = oldMonth8,
    oldMonth9 = oldMonth9,
    oldMonth10 = oldMonth10,
    oldMonth11 = oldMonth11,
    oldMonth12 = oldMonth12,
    prow = prow,
    requestNumber = requestNumber,
    requestType = requestType,
    insuredId = insuredId,
    workshopId = workshopId,
    userDesc = userDesc,
    workshopName = workshopName,
    year = year,
)
