package com.tamin.taminhamrah.model.occurrence

data class OccurrenceSubmitRequestDN(
    val nationalCode: String,
    val firstName: String,
    val lastName: String,
    val gender: Int,
    val nationalityCode: Int,
    val insuranceType: String,
    val insuranceTypeCode: String,
    val insuranceNumber: String,
    val branchCode: String,
    val branchName: String,
    val birthDate: Long,
    val workshopId: String,
    val workshopBranchCode: String,
    val workshopName: String,
    val employerName: String,
    val employerPhone: String,
    val workshopAddress: String,
    val workshopPostalCode: String,
    val workshopPhone: String,
    val employmentDate: Long,
    val maritalStatus: Int,
    val jobTitle: String,
    val workLocation: String,
    val transportation: String,
    val workStartTime: String,
    val workEndTime: String,
    val homeAddress: String,
    val homePhone: String,
    val homePostalCode: String,
    val accidentDate: Long,
    val accidentTime: String,
    val accidentOutcomeId: Int,
    val exactLocation: String,
    val description: String,
    val reporterType: String,
    val documents: List<OccurrenceUploadedDocDN>,
)

data class OccurrenceUploadedDocDN(
    val typeId: Int,
    val typeName: String,
    val fileName: String,
    val guid: String,
)
