org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
kotlin.code.style=official
android.useAndroidX=true
android.memory.heapSize=4096m
android.nonTransitiveRClass=true
android.builder.sdkDownload=false
kotlin.native.ignoreDisabledTargets=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
