package com.tamin.taminhamrah.model.contracts

data class ContractDN(
    val adultLetterDate: String?,
    val adultLetterNumber: String?,
    val age: String?,
    val branchCode: String?,
    val brchCodeNew: String?,
    val cancelDate: Long?,
    val cancelUID: String?,
    val canceldesc: String?,
    val cityCode: String?,
    val cntDrmn: String?,
    val cntFreeJobCode: String?,
    val cntIncPayDate3t4: String?,
    val cntMedicalFlag: String?,
    val comment: String?,
    val commissionStatus: String?,
    val confirmDate: Long?,
    val confirmUID: String?,
    val contractDate: Long?,
    val contractNumber: Int?,
    val contractStatus: String?,
    val contractStatusObject: ContractStatusObjectDN?,
    val creatDate: Long?,
    val createDate: Long?,
    val createUID: String?,
    val eligibilityStatus: String?,
    val freeJob: FreeJobDN?,
    val guid: String?,
    val guidName: String?,
    val history: String?,
    val insuranceId: String?,
    val isStudent: String?,
    val medicalExemptionStatus: String?,
    val militaryServiceLicense: String?,
    val mobileNumber: String?,
    val natinoalCode: String?,
    val physicalStatus: String?,
    val premiumRate: PremiumRateDN?,
    val premiumRateCode: String?,
    val premiumType: PremiumTypeDN?,
    val premiumTypeCode: String?,
    val provinceCode: String?,
    val provinceName: String?,
    val refCode: String?,
    val salary: Long?,
    val startDate: Long?,
    val statusDate: Long?,
    val wage: Int?,
)

data class ContractStatusObjectDN(
    val selfIsuContStatDesc: String?,
    val selfIsuContStatCode: Int?,
)

data class PremiumTypeDN(
    val insuranceDescription: String?,
    val insuranceKind: String?,
    val insuranceTypeCode: String?,
    val status: String?,
    val statusDate: Long?,
)

data class PremiumRateDN(
    val govermentPercent: String?,
    val insurDpercent: String?,
    val payrespitelOne: String?,
    val payrespitelTwo: String?,
    val selfIsuTypeCode: String?,
    val spcLowDayWage: String?,
    val spcrateCode: String?,
    val spcrateDescription: String?,
    val status: String?,
    val statusStDate: String?,
    val treatmentPercap: String?,
)

data class FreeJobDN(
    val discrioption: String?,
    val endDate: String?,
    val fixRank: String?,
    val id: Int?,
    val iscoCode: String?,
    val jobCode: String?,
    val startDate: String?,
    val status: String?,
)
