package com.tamin.taminhamrah.di


import com.tamin.taminhamrah.useCases.addDependent.AddNewDependentUseCase

val domainModule = module {
    // Add Dependent UseCases
    factoryOf(::GetActiveBranchesUseCase)
    factoryOf(::GetFamilyRelationshipsFromProxyUseCase)
    factoryOf(::GetFamilyRelationshipsUseCase)
    factoryOf(::InquiryRegistryUseCase)
    factoryOf(::InquiryEducationCodeUseCase)
    factoryOf(::UploadDependentImageUseCase)
    factoryOf(::AddNewDependentUseCase)
    factoryOf(::GetDependentInfoUseCase)
    factoryOf(::DeepLinkManagerImpl) bind DeepLinkManager::class
    factoryOf(::AuthAuthorizeUrlUseCaseImpl) bind AuthAuthorizeUrlUseCase::class
    factoryOf(::ExchangeCodeForTokensUseCaseImpl) bind ExchangeCodeForTokensUseCase::class
    factoryOf(::DebugClientCredentialsLoginUseCaseImpl) bind DebugClientCredentialsLoginUseCase::class
    factoryOf(::HandleAuthDeepLinkUseCaseImpl) bind HandleAuthDeepLinkUseCase::class
    factoryOf(::UserProfileImageUseCase)
    factoryOf(::TaminRelationUseCase)
    factoryOf(::IdentityInfoUseCase)
    factoryOf(::GetPensionInquiryUseCase)
    factoryOf(::SendRequestInquirePensionCertificateUseCase)
    factoryOf(::GetPensionerIdUseCase)
    factoryOf(::SendRequestInquirePensionCertificateUseCase)
    factoryOf(::SendRequestDeferredInstallmentCertificateUseCase)
    factoryOf(::GetPensionerPayRollUseCase)
    factoryOf(::GetPensionerPayRollPDFUseCase)
    factoryOf(::SendPayRollToInboxUseCase)
    factoryOf(::GetUserAgeUseCase)
    factoryOf(::GetRetirementRequestInfoUseCase)
    factoryOf(::CheckRetirementStatusUseCase)
    factoryOf(::GetAuthenticationCodeUseCase)
    factoryOf(::AuthenticationAndGetPersonalInfoUseCase)
    factoryOf(::CreateRetirementRequestUseCase)
    factoryOf(::SendRetirementDocumentUseCase)
    factoryOf(::GetEdictPensionerUseCase)
    factoryOf(::GetEdictReportPDFUseCase)
    factoryOf(::SendEdictPensionerToMyInboxUseCase)
    factoryOf(::SendImageRequestUseCase)
    factoryOf(::SubdominantUseCase)
    factoryOf(::MockSubdominantUseCase)
    factoryOf(::SignOutUseCase)
    factoryOf(::GetSignOutUrlUseCase)
    factoryOf(::GetBankAccountListUseCase)
    factoryOf(::RegisterBankAccountUseCase)
    factoryOf(::GetInsuredActiveBranchUseCase)
    factoryOf(::GetRelationTaminAllUseCase)
    factoryOf(::GetStatusCertificateReportUseCase)
    factoryOf(::GetWageCertificateReportUseCase)
    factoryOf(::GetIdentityInfoUseCase)
    factoryOf(::GetRecipientsUseCase)
    factoryOf(::GetElectronicFileUseCase)
    factoryOf(::DownloadDocumentUseCase)
    factoryOf(::GetRecipientListUseCase)
    factoryOf(::GetPersonalInfoUseCase)
    factoryOf(::GetDeceasedInfoUseCase)
    factoryOf(::GetDisabilityDependentInfoUseCase)
    factoryOf(::GetSurvivorListUseCase)
    factoryOf(::CheckGirlSurvivorConditionsUseCase)
    factoryOf(::GetGirlSurvivorReportUseCase)
    factoryOf(::ConfirmGirlSurvivorUseCase)
    factoryOf(::GetConfirmSurvivorsListUseCase)
    factoryOf(::SaveSurvivorInfoUseCase)
    factoryOf(::GetFinalSurvivorPensionPDFUseCase)
    factoryOf(::SubmitFinalSurvivorPensionUseCase)
    factoryOf(::GetAgeUseCase)
    factoryOf(::GetCitiesUseCase)
    factoryOf(::GetCityUseCase)
    factoryOf(::GetProvincesUseCase)
    factoryOf(::GetCitiesByProvinceUseCase)
    factoryOf(::GetInsuranceTypesUseCase)
    factoryOf(::CheckUserTypeUseCase)
    factoryOf(::ChangeMobileUseCase)
    factoryOf(::VerifyChangeMobileUseCase)
    factoryOf(::GetBeneficiaryUseCase)
    factoryOf(::GetMainMenuUseCase)
    factoryOf(::GetUserRequestsUseCase)
    factoryOf(::GetUserRequestTypesUseCase)
    factoryOf(::GetUserRequestErrorsUseCase)
    factoryOf(::GetSmartGuideListUseCase)
    factoryOf(::GetUserRequestDetailUseCase)
    factoryOf(::GetShowRequestInfoUseCase)
    factoryOf(::DownloadUserRequestDocumentUseCase)
    factoryOf(::CheckHistoryObjectionStatusNotExistUseCase)
    factoryOf(::GetHistoryObjectionNotExistRequestsUseCase)
    factoryOf(::SaveHistoryObjectionNotExistRequestUseCase)
    factoryOf(::DeleteHistoryObjectionNotExistRequestUseCase)
    factoryOf(::ConfirmHistoryObjectionNotExistUseCase)
    factoryOf(::FinalConfirmHistoryObjectionNotExistUseCase)

    factoryOf(::GetTalfighInfosUseCase)
    factoryOf(::GetUserInfosUseCase)
    factoryOf(::GetUserRoleUseCase)
    factoryOf(::DownloadHistoryReportUseCase)
    factoryOf(::SendHistoryNoticeUseCase)
    factoryOf(::GetDastmozdInfosUseCase)
    factoryOf(::GetHistoryJobInfosUseCase)
    factoryOf(::GetMultipleWorkshopPersonalInfoUseCase)
    factoryOf(::CheckMultipleWorkshopsUseCase)
    factoryOf(::CalculateMultipleWorkshopsPensionUseCase)
    factoryOf(::CalculateWagePensionUseCase)
    factoryOf(::GetPersonalInboxItemsUseCase)
    factoryOf(::GetPersonalInboxItemsPageUseCase)
    factoryOf(::GetPersonalInboxSizeUseCase)
    factoryOf(::GetRequestInsuredMainInfoUseCase)
    factoryOf(::GetInsuredPersonsUseCase)
    factoryOf(::SaveShortTermOrthosisUseCase)
    factoryOf(::GetDataForEducationUseCase)
    factoryOf(::InquiryEducationCertificateUseCase)
    factoryOf(::CheckFractionAgeAndHistoryUseCase)
    factoryOf(::MakeFractionContractUseCase)
    factoryOf(::GetWeddingPresentInfoUseCase)
    factoryOf(::SubmitWeddingPresentUseCase)
    factoryOf(::CalculateMarriageAllowanceUseCase)
    factoryOf(::GetIllDaysInsuredMainInfoUseCase)
    factoryOf(::GetCovidResultUseCase)
    factoryOf(::CalcIllnessAmountUseCase)
    factoryOf(::SendRequestForIllDayUseCase)
    factoryOf(::GetPregnancyMainInfoUseCase)
    factoryOf(::GetPregnancyStatusListUseCase)
    factoryOf(::GetPregnancyTypeListUseCase)
    factoryOf(::SendPregnancyPayRequestUseCase)
    factoryOf(::CalculatePregnancyPayEstimateUseCase)
    factoryOf(::GetMyRequestPdfUseCase)
    factoryOf(::DeleteMyRequestUseCase)
    factoryOf(::InboxInquiryLicenseUseCase)
    factoryOf(::GetContractsUseCase)
    factoryOf(::GetContractsPageUseCase)
    factoryOf(::GetContractStatesUseCase)
    factoryOf(::CancelContractUseCase)
    factoryOf(::GetContractPaymentHistoryUseCase)
    factoryOf(::DownloadContractReportUseCase)
    factoryOf(::GetContractDebitUseCase)
    factoryOf(::GetContractLastPaymentUseCase)
    factoryOf(::GetPaymentCalculationDetailsUseCase)
    factoryOf(::GetRegistrationInfoUseCase)
    factoryOf(::GetBranchesUseCase)
    factoryOf(::GetSpcPremiumRatesUseCase)
    factoryOf(::GetFreelancePremiumRangeUseCase)
    factoryOf(::GetOptionalPremiumRangeUseCase)
    factoryOf(::CheckRedCrossStatusUseCase)
    factoryOf(::CheckMedicalStudentUseCase)
    factoryOf(::CalculateFreelanceSalaryUseCase)
    factoryOf(::CalculateOptionalSalaryUseCase)
    factoryOf(::MakeContractUseCase)
    factoryOf(::MakeFreelanceContractByGuardianUseCase)
    factoryOf(::MakeOptionalContractByGuardianUseCase)
    factoryOf(::UpdateContractUseCase)
    factoryOf(::UpdateFreelanceContractByGuardianUseCase)
    factoryOf(::UpdateOptionalContractByGuardianUseCase)
    factoryOf(::GetInsurancePaymentUseCase)
    factoryOf(::CheckInsurancePaymentStatusUseCase)
    factoryOf(::SaveContactUseCase)
    factoryOf(::GetFreeJobWagesUseCase)
    factoryOf(::UploadImageUseCase)
    factoryOf(::GetDisabilityPersonalInfoUseCase)
    factoryOf(::SaveDisabilityUserInfoUseCase)
    factoryOf(::FinalConfirmDisabilityRequestUseCase)
    factoryOf(::SaveDocumentDisabilityUseCase)
    factoryOf(::GetMedicalCommissionPdfUseCase)
    factoryOf(::GetRegisteredMedicalCommissionUseCase)
    // Agent
    factoryOf(::SendAgentPromptUseCase)
    factoryOf(::CheckChatAllowedUseCase)
    // Agent conversation cache
    factory<GetCurrentUserNationalCodeUseCase> { GetCurrentUserNationalCodeUseCaseImpl(get()) }
    factoryOf(::PruneEmptyAgentSessionUseCase)
    factoryOf(::GetAgentSessionsUseCase)
    factoryOf(::GetAgentSessionUseCase)
    factoryOf(::StartAgentSessionUseCase)
    factoryOf(::SaveCachedMessageUseCase)
    factoryOf(::GetCachedMessagesUseCase)
    factoryOf(::ObserveCachedMessagesUseCase)
    factoryOf(::DeletePendingAgentMessagesUseCase)
    factoryOf(::DeleteAgentSessionUseCase)
    factoryOf(::UpdateAgentSessionUseCase)

    factoryOf(::SendRetirementDocumentUseCase)
    factoryOf(::CreateRetirementRequestUseCase)
    factoryOf(::GetRolesUseCase)


    // Treatment UseCases
    factoryOf(::GetDeservedTreatmentUseCase)
    factoryOf(::GetElectronicPrescriptionListUseCase)
    factoryOf(::GetElectronicPrescriptionDetailUseCase)
    factoryOf(::GetElectronicPrescriptionPriceUseCase)
    factoryOf(::GetDependantUnderEighteenUseCase)
    factoryOf(::GetPrescriptionPdfFileUseCase)
    factoryOf(::DownloadLabResultPdfUseCase)
    factoryOf(::GetUserProfileUseCase)
    factoryOf(::GetCurrentUserUseCase)
    factoryOf(::GetJobTitleUseCase)
    factoryOf(::GetRegistrationDeclarationFormUseCase)
    factoryOf(::GetRequestSummaryUseCase)
    factoryOf(::PutInsuredRegistrationDocListUseCase)
    factoryOf(::CheckUserIsNewUseCase)
    // کارگاه‌های کارفرما — the list, then one group per action it launches
    factoryOf(::GetEmployerAgreementsUseCase)
    factoryOf(::GetContractRowsWithAgreementUseCase)
    factoryOf(::GetAssignerContractsUseCase)
    factoryOf(::GetComputationalBasesUseCase)
    factoryOf(::GetComputationalBasePdfUseCase)
    factoryOf(::GetSettlementSubjectsUseCase)
    factoryOf(::UploadSettlementPdfUseCase)
    factoryOf(::SubmitSettlementRequestUseCase)
    factoryOf(::GetContractRowsWithoutAgreementUseCase)
    factoryOf(::GetPaymentSheetsUseCase)
    factoryOf(::GetDebitReasonsUseCase)
    factoryOf(::GetWorkshopDebitsUseCase)
    factoryOf(::GetDemandDocumentsUseCase)
    factoryOf(::GetDebitTurnoverPdfUseCase)
    factoryOf(::PayWorkshopDebitUseCase)

    // Shared payment flow. VerifyPaymentUseCase collects every PaymentVerifier registered by any
    // feature module — getAll() is what lets a feature contribute one without core-domain, or this
    // list, having to know that the feature exists.
    factoryOf(::GetPaymentPreviewUseCase)
    factoryOf(::CreatePaymentLinkUseCase)
    factoryOf(::CancelPaymentUseCase)
    factory { VerifyPaymentUseCase(repository = get(), verifiers = getAll()) }
    factoryOf(::GetWorkshopDebtInquiryUseCase)
    factoryOf(::GetObjectionableDebitsUseCase)
    factoryOf(::CheckObjectionDeadlineUseCase)
    factoryOf(::SaveDebitObjectionUseCase)
    factoryOf(::GetDebitObjectionPdfUseCase)
    factoryOf(::GetWorkShopObjectionsUseCase)
    factoryOf(::GetWorkShopObjectionSmsUseCase)
    factoryOf(::GetRecentlyAddedMembersUseCase)
    factoryOf(::ConfirmRecentlyAddedMemberUseCase)
    factoryOf(::DeleteRecentlyAddedMemberUseCase)
    factoryOf(::CheckNewMemberIsNewUseCase)
    factoryOf(::CreateNewMemberRegistrationUseCase)
    factoryOf(::GetArticleSixteenDebtsUseCase)
    factoryOf(::GetArticleSixteenWorkshopInfoUseCase)
    factoryOf(::GetArticleSixteenRequestInfoUseCase)
    factoryOf(::SaveArticleSixteenRequestUseCase)
    factoryOf(::GetArticleSixteenReportPdfUseCase)
    factoryOf(::GetWorkshopMembersUseCase)
    factoryOf(::GetWorkshopStackHoldersUseCase)
    factoryOf(::GetLegalRepresentativeWorkshopsUseCase)
    factoryOf(::GetLegalRepresentativesUseCase)
    factoryOf(::GetLegalRepresentativeWorkshopContractsUseCase)
    factoryOf(::RequestLegalRepresentativeTicketUseCase)
    factoryOf(::VerifyLegalRepresentativeTicketUseCase)
    factoryOf(::SubmitLegalRepresentativeUseCase)
    factoryOf(::DeleteLegalRepresentativeUseCase)
    // خدمات غیرحضوری کارفرما — the employerEservicesAgreement stepper + management drill-downs
    factoryOf(::RequestEmployerAgreementTicketUseCase)
    factoryOf(::GetEmployerAgreementContactInfoUseCase)
    factoryOf(::GetWorkshopsWithoutContractUseCase)
    factoryOf(::GetWorkshopContractRowsUseCase)
    factoryOf(::SubmitEmployerAgreementUseCase)
    factoryOf(::GetLegalDocumentUseCase)
    factoryOf(::GetTreatmentCostsUseCase)
    factoryOf(::GetTreatmentCostsPDFUseCase)
    factoryOf(::SendToInboxTreatmentCostsUseCase)
    factoryOf(::GetMedicalConfirmationsUseCase)
    factoryOf(::GetMedicalConfirmationPDFUseCase)
    factoryOf(::SendToInboxMedicalConfirmationUseCase)


    // Health UseCases
    factoryOf(::GetPatientGeneralUseCase)
    factoryOf(::GetPatientSelfDeclarativeUseCase)
    factoryOf(::GetPatientDrugAllergiesUseCase)
    factoryOf(::GetPatientHospitalizationsUseCase)
    factoryOf(::GetPatientVisitsUseCase)
    factoryOf(::GetPatientLabsUseCase)
    factoryOf(::GetPatientImagingUseCase)
    factoryOf(::GetVersionHistoryUseCase)
    factoryOf(::SetThemeUseCase)
    factoryOf(::SetBiometricEnabledUseCase)
    factoryOf(::CompleteBiometricEnrollmentPromptUseCase)
    factoryOf(::SetFontSizeUseCase)
    factoryOf(::GetAllProvincesUseCase)
    factoryOf(::GetProvinceCitiesUseCase)
    factoryOf(::GetBloodGroupsUseCase)
    factoryOf(::GetMaritalStatusUseCase)
    factoryOf(::GetRelationTypesUseCase)
    factoryOf(::GetSmokingStatusUseCase)
    factoryOf(::GetSelfDeclarableIllnessesUseCase)
    factoryOf(::GetSelfDeclarableIllnessesByGroupUseCase)
    factoryOf(::GetAllDrugsUseCase)
    factoryOf(::UpdatePatientUseCase)
    factoryOf(::AddSelfDeclarativeUseCase)
    factoryOf(::UpdateSelfDeclarativeUseCase)
    factoryOf(::SyncIllnessSelfDeclarativesUseCase)
    factoryOf(::SyncDrugAllergiesUseCase)
    factoryOf(::GetActFrequenciesUseCase)
    factoryOf(::GetContactUsUseCase)

    // Add Dependent UseCases
    factoryOf(::GetDependentInfoUseCase)
    factoryOf(::GetActiveBranchesUseCase)
    factoryOf(::GetFamilyRelationshipsUseCase)
    factoryOf(::GetFamilyRelationshipsFromProxyUseCase)
    factoryOf(::InquiryRegistryUseCase)
    factoryOf(::InquiryEducationCodeUseCase)
    factoryOf(::UploadDependentImageUseCase)
    factoryOf(::AddNewDependentUseCase)
    factoryOf(::RefreshDependentsUseCase)

    // Employer Info UseCases
    factoryOf(::GetLegalWorkshopUseCase)
    factoryOf(::GetLegalWorkshopCeoUseCase)
    factoryOf(::RequestLegalTicketUseCase)
    factoryOf(::SubmitLegalWorkshopInfoUseCase)
    factoryOf(::RequestRealTicketUseCase)
    factoryOf(::SubmitRealWorkshopInfoUseCase)

    // Stories UseCases
    factoryOf(::GetStoryChannelsUseCase)
    factoryOf(::ObserveSeenStoryChannelsUseCase)
    factoryOf(::MarkStoryChannelSeenUseCase)
    factoryOf(::ObserveStoryEngagementUseCase)
    factoryOf(::ToggleStoryLikeUseCase)
    factoryOf(::ToggleStorySaveUseCase)
}

