package com.tamin.taminhamrah.model.objectionInsurance

data class ObjectionInsuranceHistoryDN(
    val branchCode: String? = null,
    val branchName: String? = null,
    val confirmed: Boolean? = null,
    val deleted: Boolean? = null,
    val historyTypeCode: String? = null,
    val historyTypeName: String? = null,
    val isDeleted: Boolean? = null,
    val newMonth1: String? = null,
    val newMonth2: String? = null,
    val newMonth3: String? = null,
    val newMonth4: String? = null,
    val newMonth5: String? = null,
    val newMonth6: String? = null,
    val newMonth7: String? = null,
    val newMonth8: String? = null,
    val newMonth9: String? = null,
    val newMonth10: String? = null,
    val newMonth11: String? = null,
    val newMonth12: String? = null,
    val oldMonth1: String? = null,
    val oldMonth2: String? = null,
    val oldMonth3: String? = null,
    val oldMonth4: String? = null,
    val oldMonth5: String? = null,
    val oldMonth6: String? = null,
    val oldMonth7: String? = null,
    val oldMonth8: String? = null,
    val oldMonth9: String? = null,
    val oldMonth10: String? = null,
    val oldMonth11: String? = null,
    val oldMonth12: String? = null,
    val prow: String? = null,
    val requestNumber: String? = null,
    val requestType: String? = null,
    val insuredId: String? = null,
    val workshopId: String? = null,
    val userDesc: String? = null,
    val workshopName: String? = null,
    val year: String = "",
)
