package com.tamin.taminhamrah.model.relation

import kotlinx.serialization.Serializable

@Serializable
data class TaminRelationPR(
    val id: Int,
    val nationalId: String,
    val insuranceId: String,
    val firstName: String,
    val lastName: String,
    val fullName: String,
    val fatherName: String,
    val identityId: String,
    val birthDate: String,
    val otherDesc: String,
    val workshopId: String,
    val workshopName: String,
    val lastMonthWork: String,
    val isuType: String,
    val isuStatus: String,
    val isuTypeDesc: String,
    val isuStatusDesc: String,
    val relationType: String,
    val relationTypeDesc: String,
    val relationWithTaminId: String,
    val relationStartDate: String,
    val brhCode: String,
    val brhName: String,
    val brhAdress: String,
    val address: String,
    val tell: String,
    val workAddress: String,
    val workTel: String,
    val employerMobile: String,
    val employerName: String,
    val bookletDate: String,
    val idCityName: String,
    val parentRisuId: String,
    val parentNationalId: String,
    val pensionerId: String,
    val parentLastName: String,
    val parentFirstName: String,
    val parentFatherName: String,
    val parentIdNumber: String,
    val parentBirthDate: String,
    val parentIdCityName: String,
    val dependenceType: String,
    val noBooklet: String,
    val haveDarman: String,
    val isuCityCode: String,
    val isuCityName: String,
    val idCityCode: String,
    val parentDeathDate: String
)
