package com.tamin.taminhamrah.model.pension.disabilityRequest.medicalCommission

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class RegisteredMedicalCommissionDTO(
    @SerialName("demandInfoId") val demandInfoId: String? = null,
    @SerialName("demandTypeCode") val demandTypeCode: String? = null,
    @SerialName("demandSaveDate") val demandSaveDate: Long? = null,
    @SerialName("commFirstName") val commFirstName: String? = null,
    @SerialName("commLastName") val commLastName: String? = null,
    @SerialName("commFatherName") val commFatherName: String? = null,
    @SerialName("commBirthDate") val commBirthDate: Long? = null,
    @SerialName("commGender") val commGender: String? = null,
    @SerialName("commMarriageStatus") val commMarriageStatus: String? = null,
    @SerialName("commIdNumber") val commIdNumber: String? = null,
    @SerialName("commExpCityCode") val commExpCityCode: String? = null,
    @SerialName("commRelationTypeCode") val commRelationTypeCode: String? = null,
    @SerialName("commNationalCode") val commNationalCode: String? = null,
    @SerialName("guardianNationalCode") val guardianNationalCode: String? = null,
    @SerialName("commInsuredTypeCode") val commInsuredTypeCode: String? = null,
    @SerialName("commResidenceCityCode") val commResidenceCityCode: String? = null,
    @SerialName("commAddress") val commAddress: String? = null,
    @SerialName("commMobileNumber") val commMobileNumber: String? = null,
    @SerialName("commTelephoneNumber") val commTelephoneNumber: String? = null,
    @SerialName("commNationality") val commNationality: String? = null,
    @SerialName("deadDate") val deadDate: Long? = null,
    @SerialName("insuranceNumber") val insuranceNumber: String? = null,
    @SerialName("pensionerCode") val pensionerCode: String? = null,
    @SerialName("isuTypeCode") val isuTypeCode: String? = null,
    @SerialName("nationalCode") val nationalCode: String? = null,
    @SerialName("referBadviCode") val referBadviCode: String? = null,
    @SerialName("status") val status: String? = null,
    @SerialName("referTypeCode") val referTypeCode: String? = null,
    @SerialName("lastJobDesc") val lastJobDesc: String? = null,
    @SerialName("lastJobCode") val lastJobCode: String? = null,
    @SerialName("jobHistoryDesc") val jobHistoryDesc: String? = null,
    @SerialName("hasDrivingCertificate") val hasDrivingCertificate: String? = null,
    @SerialName("hasVisitBeforeJob") val hasVisitBeforeJob: String? = null,
    @SerialName("hasVisitInJob") val hasVisitInJob: String? = null,
    @SerialName("hasHealthyCertificate") val hasHealthyCertificate: String? = null,
    @SerialName("hasContract") val hasContract: String? = null,
    @SerialName("hasExpertJob") val hasExpertJob: String? = null,
    @SerialName("historyConfirm") val historyConfirm: String? = null,
    @SerialName("militaryStatusCode") val militaryStatusCode: String? = null,
    @SerialName("commissionInResidenceCity") val commissionInResidenceCity: String? = null,
    @SerialName("dependencyTypeCode") val dependencyTypeCode: String? = null,
    @SerialName("branchCode") val branchCode: String? = null,
    @SerialName("divan") val divan: String? = null,
    @SerialName("isConfirmed") val isConfirmed: String? = null,
    @SerialName("refId") val refId: String? = null,
    @SerialName("commPostalCode") val commPostalCode: String? = null,
    @SerialName("commCaseTypeCode") val commCaseTypeCode: String? = null,
    @SerialName("isuStatusTypeCode") val isuStatusTypeCode: String? = null,
    @SerialName("demandStage") val demandStage: String? = null,
    @SerialName("sendCentralCommittee") val sendCentralCommittee: String? = null,
    @SerialName("commissionCentralId") val commissionCentralId: String? = null,
    @SerialName("commissionPollDesc") val commissionPollDesc: String? = null,
    @SerialName("committeeRequestInfoList") val committeeRequestInfoList: List<CommitteeRequestInfoDTO>? = null,
    @SerialName("committeeDemandInfoDocumentList") val committeeDemandInfoDocumentList: List<CommitteeDemandInfoDocumentDTO>? = null,
)
