package com.tamin.taminhamrah.model.common

sealed class FeatureStatus {
    object Enabled : FeatureStatus()
    data class Disabled(val message: String?) : FeatureStatus()
    data class TemporaryDisabled(val message: String?) : FeatureStatus()
    data class EnabledWithError(val message: String?) : FeatureStatus()
    data class WebView(val url: String) : FeatureStatus()
}

enum class FeatureFlag(val id: Int) {
    IDENTITY_INFO(1),
    ACTIVE_RELATION(2),
    BANK_ACCOUNT_LIST(3),
    EDIT_IMAGE(4),
    DEPENDENTS(5),
    MERGE_HISTORY(6),
    WAGE_AND_HISTORY(7),
    COMBINED_RECORD(8),
    SEND_INSURANCE_HISTORY_TO_INSTITUTION(9),
    OBJECTION_NON_EXISTENT_HISTORY(10),
    VIEW_TITLE_JOB(11),
    VIEW_SHORT_TERM(13),
    WEDDING_PRESENT(14),
    OROTEZ_PROTEZ(15),
    REQUEST_FOR_PREGNANCY_PAY(16),
    REQUEST_PAYMENT_FOR_ILL_DAYS(17),
    REQUEST_FUNERAL_GRANT(18),
    LIST_OF_INSPECTIONS_PERFORMED(19),
    CALCULATE_MARRIAGE_ALLOWANCE(20),
    CALCULATE_WAGE_ILL_DAYS(21),
    CALCULATE_WAGE_PREGNANCY(22),
    CALCULATE_WAGE_PENSION(23),
    DESERVED_TREATMENT(25),
    PRESCRIPTION(26),
    FREELANCE_INSURANCE(33),
    STUDENT_INSURANCE(34),
    CONTRACTS(35),
    HOUSEWIFE_INSURANCE(36),
    OPTIONAL_INSURANCE(37),
    INQUIRY_EDUCATION(38),
    FRACTION_CONTRACT(39),
    REQUEST_PENSION_BY_SURVIVOR(40),
    RETIREMENT_PENSION(41),
    OBJECTION_INSURANCE_HISTORY(42),
    OBJECTION_INSURANCE_HISTORY_45(45),
    MY_ELECTRONIC_FILE(46),
    WORKERS_PAYMENT_INFO(47),
    DESERVED_TREATMENT_101(101),
    PRESCRIPTION_102(102),
    PENSION_INQUIRY(104),
    PAY_ROLL(105),
    EDICT_PENSIONER(106),
    ISSUANCE_WAGE_CERTIFICATE(107),
    DEFERRED_INSTALLMENT_CERTIFICATE(108),
    CALCULATE_WAGE_PENSION_109(109),
    GIRL_SURVIVOR(110),
    REQUEST_PENSION_BY_SURVIVOR_112(112),
    DISABILITY_PENSION(113),
    WORKSHOPS(1001),
    CONTRACT_INFO(1002),
    ASSIGNER_CONTRACT(1003),
    COMPLETE_WORKSHOP_INFO(1004),
    STACK_HOLDER_LIST(1005),
    FOLLOW_PROTEST_STATUS(1006),
    REGISTER_AGREEMENT(1007),
    PERFORMED_INSPECTION(1008),
    INSTALLMENT_DEBT(1009),
    CONSTRUCTION_INSURANCE(1010),
    OCCURRENCE(1011),
    LAWS(1012);

    companion object {
        fun fromId(id: Int?) = entries.find { it.id == id }
    }
}
