package com.tamin.taminhamrah.model.pension.disabilityRequest.medicalCommission

data class CommitteeRequestInfoDN(
    val requestInfoId: String? = null,
    val requestNumber: String? = null,
    val committeeDemandInfo: String? = null,
    val doctorInfoId: String? = null,
    val requestSaveDate: Long? = null,
    val hasDrugUsage: String? = null,
    val hasSurgery: String? = null,
    val hasHospitalization: String? = null,
    val hasOtherDoctor: String? = null,
    val hasOtherDarman: String? = null,
    val otherDarmanDesc: String? = null,
    val hasCommissionOtherOrgan: String? = null,
    val hasCommissionTaminOrgan: String? = null,
    val commissionOtherOrganDesc: String? = null,
    val hasSupportOrgan: String? = null,
    val supportOrganDesc: String? = null,
    val bookletTypeCode: String? = null,
    val refrenceReasonCode: String? = null,
    val darmanDocument: String? = null,
    val illnessDesc: String? = null,
    val mainDoctorFirstName: String? = null,
    val mainDoctorLastName: String? = null,
    val mainDoctorSpeciality: String? = null,
    val hasDrugUsageBoolean: Boolean? = null,
    val hasSurgeryBoolean: Boolean? = null,
    val hasOtherDarmanBoolean: Boolean? = null,
    val committeeRequestInfoDocumentList: List<CommitteeRequestInfoDocumentDN>? = null,
)
